name: rechnung
on: [push]

jobs:
  make_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            make
  make_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            make example
  rechnung_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: rechnung.sty und rechnung.pdf erstellen
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            latex rechnung.ins
            pdflatex rechnung.dtx
      - name: rechnung.pdf speichern
        uses: actions/upload-artifact@v3
        with:
          name: rechnung.pdf
          path: rechnung.pdf
