name: rechnung
on: [push]

jobs:
  make_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make
  make_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make test
  rechnung_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latex rechnung.ins
            pdflatex rechnung.dtx
      - name: rechnung.pdf speichern
        uses: actions/upload-artifact@v4
        with:
          name: rechnung.pdf
          path: rechnung.pdf
