name: rechnung
on: [push]

jobs:
  make_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action/full@v2
        with:
          run: |
            make
  make_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action/full@v2
        with:
          run: |
            make test
  rechnung_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: rechnung.sty und rechnung.pdf erstellen
        uses: xu-cheng/texlive-action/full@v2
        with:
          run: |
            latex rechnung.ins
            pdflatex rechnung.dtx
      - name: rechnung.pdf speichern
        uses: actions/upload-artifact@v3
        with:
          name: rechnung.pdf
          path: rechnung.pdf
